hollymovies/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from viewer.models import Genre, Movie, Actor, Building, Comment
from viewer.views import mypage, hello, search, MoviesView, MovieCreateView, MovieUpdateView, MovieDeleteView, tags_example
from viewer.views import SubmittablePasswordChangeView, SignUpView, GenresView, GenreCreateView, GenreUpdateView, GenreDeleteView
from viewer.views import BuildingView, BuildingCreateView, BuildingUpdateView, BuildingDeleteView, CommentCreateView
from viewer.views import api_moviesgetall, list_movies
from django.contrib.auth import views

admin.site.register(Genre)
admin.site.register(Movie)
admin.site.register(Actor)
admin.site.register(Building)
admin.site.register(Comment)
from django.contrib.auth.models import Permission
admin.site.register(Permission)
from viewer.views import add_user_to_group

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mypage/', mypage, name='mypage'),

    path('hello/<s0>', hello),
    path('tags_example', tags_example),
    path("add_user_to_group", add_user_to_group),
    # path('', views.movies), #Function based view
    path('', MoviesView.as_view(), name='index'),  # Class based view
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),


    path('genres', GenresView.as_view(), name='genres'),  # Class based view
    path('genre/create', GenreCreateView.as_view(), name='genre_create'),
    path('genre/update/<pk>', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<pk>', GenreDeleteView.as_view(), name='genre_delete'),
    path('search', search, name='search'),  # Class based view


    path('building', BuildingView.as_view(), name='building'),
    path('building/create', BuildingCreateView.as_view(), name='building_add'),
    path('building/update/<pk>', BuildingUpdateView.as_view(), name='building_update'),
    path('building/delete/<pk>', BuildingDeleteView.as_view(), name='building_delete'),

    path('comment/create/<pk>', CommentCreateView.as_view(), name='comment_add'),


    path('api/movies/get_all', api_moviesgetall, name='api_moviesgetall'),




    path('list_movies', list_movies, name='list_movies'),
]

viewer/models.py
from django.db.models import (
  DO_NOTHING, CharField, DateField, DateTimeField, ForeignKey, IntegerField,
  Model, TextField, ManyToManyField
)


class Genre(Model):
  name = CharField(max_length=128)



class Movie(Model):
  title = CharField(max_length=128)
  genre = ForeignKey(Genre, on_delete=DO_NOTHING)
  rating = IntegerField()
  released = DateField()
  description = TextField(default="no description")
  created = DateTimeField(auto_now_add=True)

class Actor(Model):
  first_name = CharField(max_length=128)
  last_name = CharField(max_length=128)
  movies = ManyToManyField(Movie)

  def __str__(self):
    return f"{self.first_name} {self.last_name}"

from django.contrib.auth import get_user_model
User = get_user_model()

class Building(Model):
  company = CharField(max_length=128)
  floors = IntegerField()
  user = ForeignKey(User, on_delete=DO_NOTHING, default=1)


class Comment(Model):
  movie = ForeignKey(Movie, on_delete=DO_NOTHING, default=1)
  text = CharField(max_length=128)

  def __str__(self):
    return f"Komentář: {self.text} k filmu {self.movie.title}"

viewer/forms.py
from django.forms import (
  CharField, DateField, Form, IntegerField, ModelChoiceField, Textarea, SelectDateWidget
)
import re
from django.forms import ModelForm
from viewer.models import Genre, Movie, Building, Comment

def capitalized_validator(value):
  if value[0].islower():
    raise ValidationError('Value must be capitalized.')
class PastMonthField(DateField):

  def validate(self, value):
    super().validate(value)
    if value >= date.today():
      raise ValidationError('Only past dates allowed here.')

  def clean(self, value):
    result = super().clean(value)
    return date(year=result.year, month=result.month, day=1)


class MovieForm(ModelForm):

  class Meta:
    model = Movie
    fields = '__all__'

  #title = CharField(validators=[capitalized_validator])
  #rating = IntegerField(min_value=1, max_value=10)
  #released = PastMonthField()

  def clean_description(self):
    # Každá věta bude začínat velkým písmenem
    initial = self.cleaned_data['description']
    sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
    return '. '.join(sentence.capitalize() for sentence in sentences)

  def clean(self):
    result = super().clean()
    if result['genre'].name == 'commedy' and result['rating'] > 5:
      raise ValidationError(
        "Commedies aren't so good to be rated over 5."
      )
    return result

class GenreForm(ModelForm):
  class Meta:
    model = Genre
    fields = '__all__'


class SearchForm(Form):
  search_field = CharField(max_length=128)


from django.contrib.auth.forms import (
  AuthenticationForm, PasswordChangeForm, UserCreationForm
)
class SignUpForm(UserCreationForm):

  class Meta(UserCreationForm.Meta):
    fields = ['username', 'first_name', 'last_name']

  def save(self, commit=True):
    self.instance.is_active = True
    return super().save(commit)




class BuildingForm(ModelForm):

  class Meta:
    model = Building
    fields = '__all__'

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['text']


viewer/views.py
from lib2to3.fixes.fix_input import context

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from viewer.models import Movie, Genre, Building, Comment
from django.views.generic import FormView, ListView, CreateView, UpdateView, DeleteView, TemplateView
from logging import getLogger
from viewer.forms import MovieForm, GenreForm, SearchForm, BuildingForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.views.generic import CreateView

from viewer.forms import (
  SignUpForm
)
from django.contrib.auth.models import User
def mypage(request):
    return render(
        request,
        "mypage.html",
        context={}
    )

def hello(request, s0):
  s1 = request.GET.get('s1', '')
  return render(
    request, template_name='hello.html',
    context={'adjectives': [s0, s1, 'beautiful', 'wonderful']}
  )

@login_required
def search(request):
    to_find = request.GET.get("search_field", "")
    return render(
        request, template_name='search.html', context={
            "movies": Movie.objects.filter(title__contains=to_find),
            "genres": Genre.objects.filter(name__contains=to_find),
            "search_form": SearchForm,
        }
    )

@login_required
def add_user_to_group(request):
    from django.contrib.auth.models import Group
    request.user.groups.add(Group.objects.first())
    pass

    return render(
        request, template_name='movies.html',
        context={'movies': Movie.objects.all()}
    )


def movies(request):

  request.user.groups.append()
  return render(
    request, template_name='movies.html',
    context={'movies': Movie.objects.all()}
  )

def tags_example(request):
  return render(
    request, template_name='tags_example.html',
    context={'movies': Movie.objects.all(),
              "first_movie": Movie.objects.first(),
              "notebooky": {
                  "Lucie": "Asus",
                  "Karel": "Lenovo",
                },
              "jmeno": "Albert",
              "vek": 77.9800,
              "kids": ["Julie", "Aleš", "Karel"],
              "lineexample": "Radek1\n radek2",
              "pocet_kusu": 6,
              "value": timezone.now()
        }
) 
LOGGER = getLogger()
  
class MoviesView(ListView):
  template_name = 'movies.html'
  model = Movie


class MovieCreateView(PermissionRequiredMixin, CreateView):

  template_name = 'form.html'
  form_class = MovieForm
  success_url = reverse_lazy('movie_create')
  permission_required = 'viewer.add_movie'

  def form_invalid(self, form):
    LOGGER.warning(f'User provided invalid data. {form.errors}')
    return super().form_invalid(form)

    
class MovieUpdateView(PermissionRequiredMixin, UpdateView):

  template_name = 'form.html'
  model = Movie
  form_class = MovieForm
  success_url = reverse_lazy('index')
  permission_required = 'viewer.change_movie'

  def form_invalid(self, form):
    LOGGER.warning('User provided invalid data while updating a movie.')
    return super().form_invalid(form)


class MovieDeleteView(DeleteView):
  template_name = 'movie_confirm_delete.html'
  model = Movie
  success_url = reverse_lazy('index')

class GenresView(LoginRequiredMixin ,ListView):
  template_name = 'genres.html'
  model = Genre

class GenreCreateView(PermissionRequiredMixin,CreateView):
  template_name = 'genre_form.html'
  form_class = GenreForm
  success_url = reverse_lazy('genres')
  permission_required = 'viewer.add_building'

  def form_invalid(self, form):
      LOGGER.warning(f'User provided invalid data. {form.errors}')
      return super().form_invalid(form)

class GenreUpdateView(UpdateView):
  template_name = 'genre_form.html'
  model = Genre
  form_class = GenreForm
  success_url = reverse_lazy('genres')

  def form_invalid(self, form):
      LOGGER.warning('User provided invalid data while updating a movie.')
      return super().form_invalid(form)

class GenreDeleteView(DeleteView):
  template_name = 'genre_confirm_delete.html'
  model = Genre
  success_url = reverse_lazy('genres')



class SignUpView(CreateView):
  template_name = 'form.html'
  form_class = SignUpForm
  success_url = reverse_lazy('index')

class SubmittablePasswordChangeView(PasswordChangeView):
    template_name = 'form.html'




class BuildingView(TemplateView):
  template_name = 'building.html'
  extra_context = {'buildings': Building.objects.all()}

class BuildingCreateView(CreateView):
  template_name = 'building_form.html'
  form_class = BuildingForm
  success_url = reverse_lazy('building')

class BuildingUpdateView(UpdateView):
  template_name = 'building_form.html'
  model = Building
  form_class = BuildingForm
  #success_url = reverse_lazy('building')

  def get_success_url(self):
      kategorie_pk = Building.objects.get(pk= self.kwargs['pk']).kategorie.pk
      return reverse_lazy('company', kwargs={'pk': kategorie_pk})

class BuildingDeleteView(DeleteView):
  template_name = 'building_form.html'
  model = Building
  success_url = reverse_lazy('building')

class CommentCreateView(FormView):
    template_name = 'form.html'
    form_class = CommentForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.movie = Movie.objects.get(pk=int(self.kwargs["pk"]))
        new_comment.save()
        return super().form_valid(form)
    pass


def api_moviesgetall(request):
    all_movies = Movie.objects.all()
    json_movies = {}
    for movie in all_movies:
        json_movies[movie.pk] = {
            "title": movie.title
        }
    return JsonResponse(json_movies)

def list_movies(request):
    import requests
    responce = requests.get("http://127.0.0.1:8000/api/movies/get_all")
    filmy = responce.json()
    return render(request, "list_movies.html", context={"movies": filmy})

viewer/templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}" {% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HollyMovies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'basic_style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container fixed">
            <a class="navbar-brand" href="{% url 'index' %}">HollyMovies</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'index' %}">
                        Movies!!!
                    </a>
                    <a class="nav-item nav-link active" href="{% url 'genres' %}">
                        Genres
                    </a>
                    <a class="nav-item nav-link active" href="{% url 'search' %}">
                        Search
                    </a>
                    {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link active" href="{% url 'logout' %}">
                        User logged in: {{ request.user.username }} - Logout
                    </a>
                    <a class="nav-item nav-link active" href="{% url 'mypage' %}">
                        My page
                    </a>

                    {% else %}
                    <a class="nav-item nav-link active" href="{% url 'login' %}">
                        Login
                    </a>
                    <a class="nav-item nav-link active" href="{% url 'sign_up' %}">
                        Sign up
                    </a>

                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
            {% block content %}{% endblock %}
        </div>
    </div>

    <span id="sdafooter"></span>
    <script src="{% static 'basic.js' %}"></script>
    <img src="{% static 'sda-logo.svg' %}" style="max-width:300px">

</body>

</html>

viewer/templates/base_alternative.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}" {% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HollyMovies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="container">
        <ul class="nav justify-content-center">
          <li class="nav-item ">
            <a class="nav-link text-danger" href="{% url 'index' %}">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'genres' %}">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}">Search</a>
          </li>
        </ul>


        {% block content %}{% endblock %}
    </div>
</body>

</html>

viewer/templates/building_form.html
{% extends 'base.html' %}

{% block content %}
<style>
table tr:nth-child(3) {
    background: #ccc;
}
</style>
<form method="POST">
    {% csrf_token %}
    <table id="building_form">
        {{form}}
    </table>
    <input type="submit" value="Hotovo">
</form>

{% endblock %}

viewer/templates/change_pass.html
{% extends "base.html" %}

{% block content %}
    <h1>Password change</h1>
  <form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

viewer/templates/form.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}



viewer/templates/genre_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %} 
    <p>
      Are you sure you want to delete genre "{{ object.name }} 
        (pk {{ object.pk }})" from database?
    </p> 
    <input type="submit" value="Submit" class="btn btn-danger">
  </form> 
{% endblock %}

viewer/templates/genre_form.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

viewer/templates/hello.html
<!DOCTYPE html>
<html>
  <body>
    <h1>Welcome to HollyMovies!</h1>
    {% for adjective in adjectives %}
      {% if adjective != 'cruel' %}
        <p>This is a {{ adjective }} world...</p>
      {% endif %}
    {% endfor %}
    GR:
    {% for group in request.user.groups.all %}
    <h3>{{ group }} </h3>
        {% for perm in group.permissions.all %}
            {{ perm }}
        {% endfor %}
    {% endfor %}
    <h5>Perm:</h5>
  {% for perm in request.user.user_permissions.all %}
  {{ perm }} - {{ perm.codename }}<br>
  {%  endfor %}
  </body>
</html>

viewer/templates/list_movies.html
{% for key, values in movies.items %}

Klíč: {{key}} Hodnota {{values.title}}<br>
{% endfor %}

viewer/templates/movie_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %} 
    <p>
      Are you sure you want to delete movie "{{ object.title }}" from database?
    </p> 
    <input type="submit" value="Submit" class="btn btn-danger">
  </form> 
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to HollyMovies!</h1>
    <a href="{% url 'movie_create' %}"> Add movie </a>

    <h1>Filmy:</h1>
    {% for movie in object_list %}

    <br>
    <br>
    <br>
      <h2>Film: {{ movie.title }} ({{ movie.released.year }}) - {{ movie.genre.name }}</h2>
            {% for actor in movie.actor_set.all %}
                <h4>Actor: {{ actor }}</h4>
            {% endfor %}
            {% for comment in movie.comment_set.all %}
                <h4 style="color: pink">Komentář: {{ comment.text }}</h4>
            {% endfor %}
          <a href="{% url 'movie_update' movie.pk %}"> Update </a>
      <a href="{% url 'movie_delete' movie.pk %}"> Delete </a>
      <a href="{% url 'comment_add' movie.pk %}"> Přidat komentář </a>


    {% endfor %}

    
{% endblock %}

viewer/templates/mypage.html
{% extends "base.html" %}

{% block content %}
  <h1>Page of user {{ request.user.username }}</h1>

    <ul>
    <li>Username {{ user.username }}</li>
    <li>First name {{ user.first_name }}</li>
    <li>Last name {{ user.last_name }}</li>
    <li>Email {{ user.email }}</li>
    <li>is_active {{ user.is_active }}</li>
    <li>date_joined {{ user.date_joined }}</li>


    </ul>
    <br>
    <a href="{% url 'password_change' %}" class="btn btn-outline-info">Change password</a>
    <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Logout</a>
    <br>
    <br>
    <h3>Oprávnění uživatele</h3>
    <table>
    <tr>
        <td><b>name</b></td>
        <td><b>codename</b></td>
    </tr>
    {% for permission in user.user_permissions.all %}
    <tr>
        <td>{{ permission }}</td>
        <td>{{ permission.codename }}</td>
    </tr>
    {% endfor %}
    </table>
    <br>
    <br>
    <h3>Skupiny uživatele</h3>
    {% for group in user.groups.all %}
        <h4>{{ group }}</h4>
        <table>
        <tr>
            <td><b>name</b></td>
            <td><b>codename</b></td>
        </tr>
        {% for permission in group.permissions.all %}
        <tr>
            <td>{{ permission }}</td>
            <td>{{ permission.codename }}</td>
        </tr>
        {% endfor %}
        </table>
    {% endfor %}

{% endblock %}

viewer/templates/search.html
{% extends 'base_alternative.html' %}

{% block content %}
    <h1>Search {{ request.user }} {{ request.user.is_authenticated }}</h1>
    <form action="{% url 'search' %}" method="GET">
    
    <table>{{ search_form }}</table>
        <input type="submit">
    </form>

    <h2>Found movies</h2>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Rating</th>
      <th scope="col">Released</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
          <th scope="row">{{ movie.pk }}</th>
          <td>{{ movie.title }}</td>
          <td>{{ movie.rating }}</td>
          <td>{{ movie.released }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

    <h2>Found genres</h2>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    {% for genre in genres %}
    <tr>
          <th scope="row">{{ genre.pk }}</th>
          <td>{{ genre.name }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

viewer/templates/tags_example.html
{% extends "base.html" %}
{% block content %}

    Jmeno: {{ jmeno }} <br>
    Jmeno upper: {{ jmeno|upper }} <br>
    Jmeno lower: {{ jmeno|lower }} <br>
    Jmeno escape: {{ jmeno|escape }} <br>
    Jmeno title: {{ jmeno|title }} <br><br>

    vek floatformat: {{ vek|floatformat  }} <br>
    vek floatformat:1: {{ vek|floatformat:1  }} <br>
    vek floatformat:"0": {{ vek|floatformat:"0"  }} <br>

    První film je: {{ first_movie.title }} s hodnocením
    {{ first_movie.rating }} <br>

    Notebook Lucie je: {{ notebooky.Lucie }} <br>
    Notebook Karla je: {{ notebooky.Karel }} <br>

    <b>kids|join:</b> {{ kids|join:"--" }}<br>
    <b>kids|first:</b> {{ kids|first }}<br>
    <b>kids|last:</b> {{ kids|last }}<br>
    <b>kids|length:</b> {{ kids|length }}<br>
    {% if kids|length == 0 %}
        Děti nejsou
    {% endif %}
    <hr>
    <b>lineexample:</b> {{ lineexample|linebreaksbr  }}<br>
    {{ kids|slice:"1:" }}<br>
    {{ "Božena je v europarlamentu"|slugify }}<br>
    {{ "Božena je v euroPARlamentu"|title }}<br>
    




{% endblock %}